name: CI

on: [push, pull_request]

jobs:
  testsuite:
    name: Tests
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.3', '8.4', '8.5']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: json, fileinfo, ctype, iconv
        tools: pecl
        coverage: pcov

    - name: Composer install
      run: composer install

    - name: Run PHPUnit
      run: |
        if [[ ${{ matrix.php-version }} == '8.3' ]]; then
          bin/phpunit --coverage-clover=coverage.xml
        else
          bin/phpunit
        fi

    - name: Code Coverage Report
      if: success() && matrix.php-version == '8.3'
      uses: codecov/codecov-action@v4

  static-analysis:
    name: PHPStan
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.3', '8.4', '8.5']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: json, fileinfo, ctype, iconv
        coverage: none
        tools: pecl

    - name: Composer install
      run: composer install

    - name: Run PHPStan
      run: bin/phpstan --error-format=github